services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.ssl:/etc/nginx/ssl:ro
      - ./.htpasswd-admin:/etc/nginx/.htpasswd-admin:ro
      - ./.htpasswd-official:/etc/nginx/.htpasswd-official:ro
      - ./web:/var/public
      - ./energymeter/viewer/web:/var/public/energymeter
    depends_on:
      - fsk-traffic
      - fsk-entry
      - fsk-queue
    networks:
      - app-network

  fsk-traffic:
    # for development
    # volumes:
    #  - ./traffic:/home/node/fsk-traffic
    image: luftaquila/fsk-traffic
    networks:
      - app-network

  fsk-entry:
    # for development
    # volumes:
    #  - ./entry:/home/node/fsk-entry
    image: luftaquila/fsk-entry
    networks:
      - app-network

  fsk-queue:
    # for development
    # volumes:
    #  - ./queue:/home/node/fsk-queue
    image: luftaquila/fsk-queue
    environment:
      - NAVER_CLOUD_ACCESS_KEY
      - NAVER_CLOUD_SECRET_KEY
      - NAVER_CLOUD_SMS_SERVICE_ID
      - PHONE_NUMBER_SMS_SENDER
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
