services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.ssl:/etc/nginx/ssl:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      - ./web:/var/public
      - ./record:/var/public/record
      - ./energymeter/viewer/web:/var/public/energymeter
    depends_on:
      - fsk-traffic
      - fsk-entry
      # - fsk-queue
    networks:
      - app-network

  fsk-traffic:
    # for development
    # volumes:
    #  - ./traffic:/home/node/fsk-traffic
    image: luftaquila/fsk-traffic
    networks:
      - app-network

  fsk-entry:
    # for development
    # volumes:
    #  - ./entry:/home/node/fsk-entry
    image: luftaquila/fsk-entry
    networks:
      - app-network

  # fsk-queue:
  #   image: 
  #   networks:
  #     - app-network
  #

networks:
  app-network:
    driver: bridge
