name: fsk-hub

services:
  nginx:
    image: nginx:latest
    ports:
      - "${PORT}:3000"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.htpasswd-ksae:/etc/nginx/.htpasswd-ksae:ro
      - ./.htpasswd-admin:/etc/nginx/.htpasswd-admin:ro
      - ./.htpasswd-official:/etc/nginx/.htpasswd-official:ro
      - ./energymeter/viewer/web:/var/public/energymeter
      - ./web:/var/public
    depends_on:
      - fsk-entry
      - fsk-queue
      - fsk-traffic
    networks:
      - app-network

  fsk-entry:
    volumes:
      - ./data/entry:/home/node/fsk-entry/data
    # build:
    #   context: ./entry
    image: luftaquila/fsk-entry:latest
    networks:
      - app-network

  fsk-queue:
    volumes:
      - ./data/queue:/home/node/fsk-queue/data
    # build:
    #   context: ./queue
    image: luftaquila/fsk-queue:latest
    environment:
      - NAVER_CLOUD_ACCESS_KEY
      - NAVER_CLOUD_SECRET_KEY
      - NAVER_CLOUD_SMS_SERVICE_ID
      - PHONE_NUMBER_SMS_SENDER
    networks:
      - app-network

  fsk-traffic:
    volumes:
      - ./data/traffic:/home/node/fsk-traffic/data
    # build:
    #   context: ./traffic
    image: luftaquila/fsk-traffic:latest
    networks:
      - app-network

  ksae-enroll:
    volumes:
      - ./data/enroll:/home/node/ksae-enroll/data
    # build:
    #   context: ./enroll
    image: luftaquila/ksae-enroll:latest
    environment:
      - NAVER_CLOUD_ACCESS_KEY
      - NAVER_CLOUD_SECRET_KEY
      - NAVER_CLOUD_SMS_SERVICE_ID
      - PHONE_NUMBER_SMS_SENDER
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
