services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.ssl:/etc/nginx/ssl:ro
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./web:/var/public:ro
    depends_on:
      - fsk-entry
      # - fsk-queue
      # - fsk-traffic
      # - fsk-energymeter
    networks:
      - app-network

  fsk-entry:
    # for development
    # volumes:
    #  - ./entry:/home/node/fsk-entry
    image: luftaquila/fsk-entry
    networks:
      - app-network
  #
  # fsk-queue:
  #   image: 
  #   networks:
  #     - app-network
  #
  # fsk-traffic:
  #   image: 
  #   networks:
  #     - app-network
  #
  # fsk-energymeter:
  #   image: 
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
